### ISSUE TITLE
Maestro controlling

### ISSUE THREAD

**Issue by jopedroliveira** [tuuzdu/crab_project#4]
Hello,
I've been studying your project in order to replicate it, however, the integration of mini-maestro seems a bit confusing, at least for me.
Do you mind explaining to me which ports are used to establish the communication interface? I could not see through the code ...

**Comment by jopedroliveira** [comment]
Sorry, meanwhile I figured out you are using a UART serial port...
FYI I am trying to implement the same system using a raspberry pi instead of BBB. Do you have any advice or concern about it?

**Comment by tuuzdu** [comment]
Hi!
It is UART. 
You can try use SPI also.

> integration of mini-maestro seems a bit confusing, at least for me.

What will you use instead?

**Comment by tuuzdu** [comment]
I think, building of project will be very same with raspberry pi.

**Comment by jopedroliveira** [comment]
Thanks. I will keep you update. As soon as I start it, I will fork your repo then submit a merge request for a raspbPi version ;) Thanks for the good work
